name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - uses: coursier/cache-action@v5
      - run: sbt -v lint
      - name: clean up
        run: "${GITHUB_WORKSPACE}/.github/clean-up.sh"
#  build:
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ ubuntu-latest ]
#        jdk: [ adopt@1.8, adopt@1.11, adopt@1.14 ]
#        scala: [ 2.11.12, 2.12.13, 2.13.5 ]
#    runs-on: ${{ matrix.os }}
#    needs: lint
#    env:
#      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
#      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
#    steps:
#    - uses: actions/checkout@v2.3.4
#      with:
#        fetch-depth: 0
#    - uses: olafurpg/setup-scala@v10
#      with:
#        java-version: ${{ matrix.jdk }}
#    - uses: coursier/cache-action@v5
#    - run: sbt -v ++${{ matrix.scala }} compile
#    - name: clean up
#      run: "${GITHUB_WORKSPACE}/.github/clean-up.sh"
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ adopt@1.8, adopt@1.11, adopt@1.14 ]
        scala: [ 2.11.12, 2.12.13, 2.13.5 ]
    runs-on: ${{ matrix.os }}
    needs: lint
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      AWS_REGION: ap-northeast-1
      TEST_TIME_FACTOR: 3
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.jdk }}
      - uses: coursier/cache-action@v5
      - uses: olafurpg/setup-gpg@v3
      - run: sbt -v ++${{ matrix.scala }} test
      - name: clean up
        run: "${GITHUB_WORKSPACE}/.github/clean-up.sh"
