name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.scala'
      - '**.java'
      - '**.sbt'
      - '.scalafmt.conf'
      - 'project/build.properties'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.scala'
      - '**.java'
      - '**.sbt'
      - '.scalafmt.conf'
      - 'project/build.properties'
      - '.github/workflows/ci.yml'
  schedule:
    - cron: '0 * * * *'
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: "adopt@1.8"
      - uses: coursier/cache-action@v6
      - run: sbt -v lint
      - name: clean up
        run: "${GITHUB_WORKSPACE}/.github/clean-up.sh"
  test:
    strategy:
      fail-fast: false
      matrix:
        jdk: [ adopt@1.8, adopt@1.11, adopt@1.14 ]
        scala: [ 3.3.0, 2.13.11, 2.12.18 ]
    runs-on: ubuntu-latest
    needs: lint
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      AWS_REGION: ap-northeast-1
      TEST_TIME_FACTOR: 3
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: ${{ matrix.jdk }}
      - uses: coursier/cache-action@v6
      - name: sbt test
        run: sbt -v ++${{ matrix.scala }} test
      - name: clean up
        run: "${GITHUB_WORKSPACE}/.github/clean-up.sh"
